### ISSUE TITLE
Dragging thumbnails cause Qelectrotech crash

### ISSUE THREAD

**Issue by glt248** [qelectrotech/qelectrotech-element-contrib#9]
Hello,

First : Thank you for your work ! 

When I'm dragging some thumbnails from Legrand folder to my folio, that cause Qelectrotech crash. But others work well.
I've tested with the reference : 40677x serie, 411506 with success, but 41070x crash every time I try... 
How can I solve this issue ?

Thank you for your reply.

I'm sharing you my installation details : 
QElectroTech V 0.90
Compilation : GCC 12.2.0
Built with Qt 5.15.7 - x86_64 - Date : Jan 6 2023 : 19:49:02 
Run with Qt 5.15.2 using 4 thread(s)
CPU : model name : Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz 
RAM Total : 15 GB
RAM Available : 11 GB
GPU : Intel Corporation HD Graphics 5500 (rev 09) 
GPU RAM : Video memory: 3072MB 
OS : linux - x86_64 - Version : Debian GNU/Linux 11 (bullseye) - Kernel : 6.0.0-0.deb11.6-amd64
*** Qt screens *** 
( 1 : 1365 x 767 )

**Comment by scorpio810** [comment]
Hello,
where is 41070 series path?
